### ISSUE TITLE
Data mismatch

### ISSUE THREAD

**Issue by aykaym** [thatguywiththatname/pcpartpickerapi#10]
Whenever I run:

`cpu_info = part_lists.get_list("cpu", page=1)`

It returns back data in the wrong variables like so:

![image](https://user-images.githubusercontent.com/40765319/57547307-da001980-7323-11e9-901b-5e0f90b34f7c.png)

I am using your most recent version after updating from an older one.

**Comment by thatguywiththatname** [comment]
Sorry about this, PCPartPicker have been changing & updating their website recently and it's difficult to keep up with what changes

I will work on updating this but i'm not sure how long it's going to take, i'm busy with exams at the moment

**Comment by aykaym** [comment]
No worries, I figured that was probably the case. Thanks for the prompt response and good luck on those exams!

**Comment by thatguywiththatname** [comment]
Thanks 😄 

Looking at the issue now, it seems like quite a simple fix. Should be able to get it done soon-ish

**Comment by thatguywiththatname** [comment]
Fix is done, it should be working now

I have pushed the new version (0.1.11) to PyPi
